apiVersion: v1
kind: Secret
metadata: 
  name: my-secrets
  labels:
    app: app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  password: {{ printf "%#v" .Values.password | b64enc | quote }}
  password_db: {{ printf "%#v" .Values.password_db | b64enc | quote }}