password: ENC[AES256_GCM,data:6JD1pEFh5X05Avr5,iv:+h2NHgfAGGdaFyfR2GMgBO3MhlEjFOIhLCADQEku+bQ=,tag:3hFQ8aD3Fq7noUQ05iLV2Q==,type:str]
password_db: ENC[AES256_GCM,data:Y0ngWiYfx0FE5cS9Hvs=,iv:DgXRau/V2FDxtozWfKTE3do5dw00H5MJ7vuHp2GBBuM=,tag:JNlDVo9KLxsaB7BVbLXiug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-28T22:24:01Z"
    mac: ENC[AES256_GCM,data:bBgrthmvtjX9h8+1LdRYqCuAhED5VSaSibNiB+UIphUjHWaSIQ9XbWnjhwiVkJKI5iEpWENjQK5b0Z6MQGh0ohwKtKKZfq4UrJe8zSvHHqU8mTfDxXp6nz+8SpiPsOimpKaeqq1mtHdrUVhTihyFuY/pdMvfqMyOFyrcA/VXUbM=,iv:a15qbndqu5mZvrUQvJbLl5vn84UGY/+lmB2FEs5BMj4=,tag:iP+F8LC9FCEk9OUSCkIm3g==,type:str]
    pgp:
        - created_at: "2024-02-28T22:23:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxy3SaeSeTZCAQ//TPj+HEEVsJUGzhgU0rtee1W3eQUgahWbIU4zxISyiTXG
            6VnFMs9GNSqo/5gzbuSQeFOUsNP+Ur1GzRlccYoPQWiNFD77qNo6Blagj6Ns/et5
            DGQX1kxw5+fj8lX/I1irCLHsAoe+sLXmuX+uYrrawyWYyfYdDw2+j8A3ornQuA0A
            ut2bKLFKIXAuPXaGmTnrttITnq1qSoJ+xwhCDYtkemSa+MoThTE27fnfS3W93mvb
            O/VjuSSuS1qvLYlWrBLChaso80xVFUNKPuNWivl3UA/kky+69WsHMA/FPvnHLry8
            ktBeyZk54T19b1eN4h6H36nQ6gWMeq5C7hMVDFC1dXODqZprjtQ7mvgTKoqOCYST
            0ErYzrRxBqdS8X6mr7VR3bJg8jH6vv7pot/XhzA/e1KenGhydnceIVZ0FWdfVRY8
            rJkK1kioprEuE/oT4UFQgGK6WaXGL5XPnXZv2S5MW6GwQaIKUK32Rb1ZTezOoHoR
            GVmnc3gjUodanBSaD2/toCe90HJAOnlbW/6hep+MFIxKjwUgWRUyU+XPbQQFXnCi
            nlwZDeFpDfs5G87qUm0NQzfJXGcS0USaOiPrbxqxwlzwFNNucFDqxGkVulzQUGFM
            JoH4IXEBfSqQ9fxfn/OllirIrEsKKOrv8yyIPMnOmfVPKEnkowDRyN2wFdESPJPU
            aAEJAhAR7da2VFdRJhaDtk9HP9OS6Itv0YG8VNpnFpkiQ0Huq1XKdWuIW7z9eB/K
            amgHJ7ocSfOpFAYPzmzw8/yuVFtTx/+FKQBkv2s2Et1fZvLdWhgZNGTxHiNyg4Pe
            NdttwNDha0Qg
            =IIfM
            -----END PGP MESSAGE-----
          fp: 56A6229CEAF2C1FA855C3C90B52D05A203060B58
    unencrypted_suffix: _unencrypted
    version: 3.8.1
